name: Build Pagefind Index
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Pagefind index
        run: npx -y pagefind@latest --site . --output-path pagefind

      - name: Commit /pagefind
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add pagefind
          git commit -m "Update Pagefind index" || echo "No changes"
          git push
