name: Build Pagefind

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Pagefind
        run: npm install pagefind@latest --no-save
      - name: Build search index (and bundle UI)
        # This writes the UI + manifest.json into /pagefind (no underscore)
        run: npx pagefind --source . --bundle-dir pagefind
      - name: Commit /pagefind to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(search): update Pagefind bundle"
          file_pattern: pagefind/**
